### PR TITLE
add autoload cookie and fix bindings for build/serve/test

### PR DESCRIPTION
**Pull request by jesse-black**

### CODE REVIEW

**Comment by jesse-black** [comment]
also submitted a PR to melpa [here](https://github.com/milkypostman/melpa/pull/2643)

**Comment by jesse-black** [comment]
I've fixed most of the things discussed at the melpa pr. For the keybindings, the [conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) say not to define C-c letter bindings because they are reserved for users, and that minor modes can use C-c punctuation bindings. How about `C-c .`?

**Comment by madnificent** [comment]
Are you picking `C-c .` for a particular reason?  I may be missing the point.  It would work for me, though perhaps it's easier to remember `C-c e`.

Do you know of any libraries that break with `C-c e`?

**Comment by jesse-black** [comment]
from the [keybinding conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) link:

> Don't define C-c letter as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the only sequences reserved for users, so do not block them.

> Sequences consisting of C-c followed by any other punctuation character are allocated for minor modes.

So users are supposed to be able to create bindings like `C-c c` or `C-c e` in their configuration files and this would overwrite that. This is a minor mode and . is punctuation, so an appropriate keybinding might be `C-c .`. This actually did happen to me, I was using `C-c c` in my configuration when I started using this and it would get overwritten.

It will be easy to configure it back to your preferred keybinding anyway.

**Comment by madnificent** [comment]
Makes perfect sense.  Seems I missed the link you included earlier.  Thanks.

**Comment by jesse-black** [comment]
Great! I hadn't changed the keybinding yet, should I make another pr or will you do it?

**Comment by madnificent** [comment]
I'm on it.

**Pull request merged**
